import Nav from "./(components)/Nav"
import Footer from "./(components)/Footer"

import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-g-black'>
        <Nav />
        <main className='mb-4 '>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
